# Generated by Django 4.0 on 2021-12-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('value', models.FloatField(verbose_name='温度')),
            ],
            options={
                'db_table': 'temp',
            },
        ),
    ]
